### ISSUE TITLE
[story] Design Info Architecture

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#100]
As a: user
I want: to see the content organized in a coherent way
So that: I can find what I'm looking for. 

Organize the following content components into logical page groups:
* Home (currently named Info)
* About
* FAQ
* Story
* Discover
* Profile?
* Today's Deck?
* Demo Decks

## Acceptance Criteria
- [x] Organize the content components 
- [x] Submit an Info Architecture (outline) as a GitHub comment
- [ ] Get @kenancasey's approval

**Comment by kenancasey** [comment]
1. Home
   1. Hero
   2. Text Blurbs
   3. Video   
   4.

**Comment by savannah-martin** [comment]
![image](https://github.com/PrayTeam/scriptured-prayer/assets/78399457/034389f8-d209-449c-9c11-19999590b384)

![image](https://github.com/PrayTeam/scriptured-prayer/assets/78399457/6084a45e-3cda-487a-ae4a-4419692eba50)

![image](https://github.com/PrayTeam/scriptured-prayer/assets/78399457/227ec8dd-0e2b-4e68-9d9e-67d4406487b0)

**Comment by sflowers51** [comment]
Home (Formerly Info)
    - Hero
    - Text Blurbs
    - Video
    - Daily Deck
    - Demo Decks
    - Faq section (formerly /faq)
    - Nav bar? 
    - Footer

Nav 
    - About Drop Down
    - Contact Drop Down
    - Discover Drop
    - Profile 
    - Settings/Sign Out Drop Down

About/Contact
    - Image
    - Contact Text Blurb
    - Privacy Policy Link
    - Footer

Settings
    - Log out button
