### ISSUE TITLE
[story] Create Nav Component

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#101]
As a: user
I want: to navigate between pages
So that: I can get to the info I want. 

## Acceptance Criteria 
- [ ] A Nav Component exists
- [ ] The Nav component includes links to all the top-level pages in the Info Arch (#100)
- [ ] The Nav component is included at the top of all the top-level pages

**Comment by asherlloyd** [comment]
@kenancasey thoughts on adding a bottom navigation bar? This seems to have become a trend in navigation within native apps as of late. I think it could work in our PWA, too:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/671ce687-ee54-4f56-9309-8f676caf4057)

**Comment by asherlloyd** [comment]
Navigation added in [v0.7.0](https://github.com/PrayTeam/scriptured-prayer/releases/tag/v0.7.0).
