### ISSUE TITLE
[BUG] Long scriptures bleed

### ISSUE THREAD

**Issue by follindown** [PrayTeam/scriptured-prayer#106]
**Describe the bug**
When the scripture is long it bleeds into the _ _ _ _ _ that tells where you are in the deck.  When we do add in instructions this will become a problem on more cards than it currently affects.

**To Reproduce**
For instance go to "I can trade in treasures on earth for ones that last by giving" in the Promises of God deck on your cell phone. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by asherlloyd** [comment]
Adding a screenshot of the defect for more information:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/7d5df6c5-c36f-485c-b28e-2c441aa36b78)

I'm not keen on the current slide markers (visually: _ _ _). It looks especially silly in circumstances where there are lots of slides - as in the shared screenshot. @kenancasey if you're onboard, let's troubleshoot other designs that could work here.

**Comment by kenancasey** [comment]
We had a PR that swapped out these markers for numbers e.g., `13/45` that I thought improved the UI. What do you think about that approach?

**Comment by asherlloyd** [comment]
@kenancasey I think that would work just fine for now. I'm going to submit a separate MR for it, however.
