### ISSUE TITLE
[BUG] Category Decks Have Cards of All Categories

### ISSUE THREAD

**Issue by Soyokaze-42** [PrayTeam/scriptured-prayer#126]
**Describe the bug**
In release 0.6.1, category decks at the bottom of the index page all have all the cards.

**To Reproduce**
Click on one of the category decks and swipe until you see a card that does not belong.

**Expected behavior**
Each deck should be limited to its category.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version Version 125.0.6422.141 (Official Build, ungoogled-chromium) (64-bit)

**Additional context**
The API call is trying to use the card_category_id filter that does not exist. That should be category_id instead.

**Comment by asherlloyd** [comment]
Resolved by #145.
