### ISSUE TITLE
Add Instructions to Homepage

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#130]
Replace "Know Him, Trust Him, Pray His Words" block with instructions.  

Know Him better.
God invites us to know Him. He reveals His character through His glorious works and the inspired Word. Scriptured Prayer directs your thoughts to God's attributes, allowing you to grow in knowledge of the Father.

Trust Him more.
Trust isn't automatic. It's a process. Just like we have to earn the trust of others, we have to learn how to trust in God. Daily prayer focused on God's Word helps prepare us for the storms of life. When trials come, we fall back on our habits. Make praise a habit through Scriptured prayer.

Pray His words.
Did you know there are 650 recorded prayers in the Bible? Why wouldn't we pray the words found in God's Holy Word? Connecting our prayers to Scripture grounds us in truth and enriches our Bible study, which in turn enriches our prayer life.

**Comment by follindown** [comment]
Scriptured Prayer is a conversation with God.  God speaks to you through the scriptures you are reading and you answer in praise, thanks, and requests.  Each of the scripture cards you encounter in your guided prayer time will require 1 of 3 actions.      
1) Repeat:  If the scripture is already in a prayer format, you can simply repeat the scripture.  For instance, "Create in me a clean heart, oh God, and renew a right spirit within me."    
2) Reword: Sometimes a scripture is nearly a prayer but needs a little editing to fit your situation.  The blessings in the Bible are a good example of this.  "May the Lord bless you and keep you and shine his face upon you and give you peace."  You only need to change a few words to turn this into a personalized prayer, "Lord bless and keep Tyler.  Shine your face upon him and give him peace."    
3) Respond: Really all that is required when you read a scripture is your heartfelt response.  "And so we know and rely on the love God has for us. God is love. Whoever lives in love lives in God, and God in them."  You might respond, "God I am so glad that your very nature is love.  Help me to love like you love."      
   
Never again will you have to wonder what to say to God. With Scriptured Prayer, your conversations will flow naturally.  As you regularly talk with God, you will come to know him better, love him more, and trust him completely.  To get a conversation with God going, try out our daily starter deck.

**Comment by asherlloyd** [comment]
@follindown while I like the specific examples in the above, I think the instructions should be made more concise. Unfortunately, there's going to be a large amount of users who simply gloss over the instructions due to their length; consider the homepage as displaying more generalized instructions (perhaps saving the more detailed steps for a dedicated "Help" section within the app). Let me know your thoughts!

**Comment by follindown** [comment]
I will see what I can do, but concise has never been my strong point.  I may refer this to Kelly and see what she can do to shorten it.
