### ISSUE TITLE
Add Close Button (x) to Upper Right of each Card

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#132]
Add close icon (x) to upper right of each card. 
Return to the previous page on click.

**Comment by asherlloyd** [comment]
Closed as part of #145 (see [`ContextualNavigation`](https://github.com/PrayTeam/scriptured-prayer/pull/145/files#diff-09a3a7817a459fd553de680b63df4529356881b6535df584d7184b774c402c7f) component).
