### ISSUE TITLE
MVP Pages

### ISSUE THREAD

**Issue by Soyokaze-42** [PrayTeam/scriptured-prayer#29]
We need the following pages for the MVP:

- [x] Homepage
    - [ ] Daily prayer (choose the prayers in the deck based on user options)
- [ ] #111
- [ ] PrayerDeck
- [ ] User Options / Profile
- [ ] User Registration (set of pages)
    - [ ] Create User
    - [ ] Login User
- [ ] Terms of Service
- [ ] Privacy Policy
- [ ] About

Include:
- [ ] Copyright
- [ ] Tutorial
- [ ] Google Analytics
- [ ] Select/Change Language (EN/ES)

**Comment by Soyokaze-42** [comment]
@kenancasey @asherlloyd Do you two think we should break this down into separate features? I really just meant for the skeleton of pages to be part of the SPA with this one. We could split it into Annon and Authenticated and hit the annon pages first.

**Comment by kenancasey** [comment]
Sure. I'm in favor of smaller units of work.
