### ISSUE TITLE
Allow FHU students to work on the project

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#43]
I'd like to use Scriptured Prayer in my Capstone course as our course project. Can we discuss allowing FHU students to work on this project, specifically v2 (custom decks/cards). 

Pros: 
- Free labor / greater productivity 
- More perspectives
- UX design from IDD majors?
- Potential marketing boost from FHU

Cons: 
- More coordination 
- Less control ?
- IP questions (I don't want FHU to get any IP rights and am willing to sign something making that official) 
- Too much CoC focus?

AC:
- [x] #46
- [ ] Define (and follow) strict contribution guidelines for code and issues
- [x] Set up branch protection rules
- [ ] Invite the students into this repository as members

**Comment by kenancasey** [comment]
Students may only work on stories with AC (i.e., stories that have been defined and planned; not feature stories). 
Student PRs must be approved by Dr. Casey (or another non-student).
Students must submit feature requests to product owner.

**Comment by Soyokaze-42** [comment]
@asherlloyd @kenancasey Did we ever get the student contribution guidelines written in a markdown file? The acceptance criteria for this one has "Define (and follow) strict contribution guidelines for code and issues" which we discussed being in the markdown file someplace, but I don't see it.

**Comment by kenancasey** [comment]
Sorry. That's still on my todo list.
