### ISSUE TITLE
[Feat] Prayer Deck Intro/Preamble Card

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#54]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
As a user, I'd like to read an intro/preamble paragraph to help set the context and build motivation for praying the upcoming prayers. 

**Describe alternatives you've considered**
I considered showing this as a modal popup (dismissable) or as static text above the cards in the prayer deck. Follin did not prefer either of those options. 

**Additional context**
This is a feature request from Follin for which she has already written content (but it hasn't been finalized and delivered). 

from #60:
This should be like the prayer prep page on this canva mockup (https://www.canva.com/design/DAF4y_Sb5ic/bVGJdbq7i8IMvPfXbGIauw/edit?utm_content=DAF4y_Sb5ic&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

This information comes from /api/categories/ as the "inspiration" string.

**Acceptance Criteria**
- [ ] Display the first so many characters of the "inspiration" text on the categories page.
- [ ] Display the whole "inspiration" text on the category detail page.

**Comment by Soyokaze-42** [comment]
I'm going to close #60, I moved the relevant info from there to here. Feel free to update this if I missed something.
