### ISSUE TITLE
Category Blurbs

### ISSUE THREAD

**Issue by follindown** [PrayTeam/scriptured-prayer#60]
As a: owner
I want: to see the beginning of a blurb explaining a category deck on the bottom of the deck front and then if you click on the deck you would be taken to a page that looks like the prayer prep page on this canva mockup (https://www.canva.com/design/DAF4y_Sb5ic/bVGJdbq7i8IMvPfXbGIauw/edit?utm_content=DAF4y_Sb5ic&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
On this page you would see the full blurb.
So that: the blurb would inform the user and give them some help in praying these decks.
This is a V2 feature.  I can do without it on the MVP b/c Ben said it would complicate things too much for us to get this in MVP by the end of this week.  
Here are the blurbs for the current categories:
Names of God
Did you know that mutual gazing can foster love and affection? It’s true in a physical sense, but it’s also true in a spiritual sense. Look upon God and grow in love with Him. Gaze at His goodness, marvel at His character, delight in His name, and draw closer to Him through praise. 

Names of Jesus
The Bible tells us that out of the overflow of the heart, the mouth speaks (Matt. 12:34). Jesus is the Word of God, the overflow of God’s heart. Meditate on the names of Jesus and see the overflow of God’s heart for you and all of mankind. 

Names of the Holy Spirit
Jesus in John 14 tells his disciples that it is better for the Holy Spirit to come than for him to stay with them.  They exchanged God with them for God in them.  When you meditate on these verses that contain the names of the Spirit, you will see all the Spirit does for you and why giving you the His Spirit was one of the most loving things Jesus could do for you.

God Is…
“God is” verses act as a checkup for your relationship with Him. Is God your joy and delight? Is God your hiding place? Your hope? Your deliverer? As you pray these verses, reflect on your relationship with your Father. Seek to draw closer in personal connection to God. 

In Christ
When we become Christians, it’s not simply a label. We take on a new identity, a new citizenship, a new set of blessings, freedoms, and rights. When God looks at us, He should see His Son. However, it can take time for us to fully internalize our new identity. Continual reminders of our new place in Christ can help us act like the citizens of heaven we are. As you pray these verses, thank God for all you have “in Christ.” 

Promises of God
Believing God’s promises is how the men and women of old showed their faith in God.   In the New Testament, God made over 100 promises to believers. What if you lived as if all the promises God has made to you are indeed "yes in Christ Jesus" (2 Cor. 1:20)?  Pray each promise expectantly, thanking Him in advance for keeping His promise, “for the one who made the promise is trustworthy” (Heb. 10:23).

AC:
- [ ] Information available in the API
- [ ] Display the first so many characters of the "inspiration" text on the categories page.
- [ ] Display the whole "inspiration" text on the category detail page.

**Comment by Soyokaze-42** [comment]
@follindown I added these blurbs as the "inspiration" text in a sheet called Category Information. These blurbs will be pulled from there when we go live if you would like to make changes.

**Comment by Soyokaze-42** [comment]
that is on the google spreadsheet we've been using.

**Comment by Soyokaze-42** [comment]
Is this related to #54?

**Comment by follindown** [comment]
Yes it is #54.  I didn't know Kenan had written one too.

**Comment by follindown** [comment]
Excellent.  I see it.
