### ISSUE TITLE
Instructional Text on Cards

### ISSUE THREAD

**Issue by follindown** [PrayTeam/scriptured-prayer#61]
As a: user
I want: to have some instructional text at the end of each card.  
So that: I will be able to pray that card more effectively.

Kelly will write one instruction for each category and I will enter any context in a column in the prayer box database for the cards that need it.  My context will override her instruction text on the cards that have context.  
This can be V2 as well if we need to do it that way to get an MVP out by Feb 12.

AC:
- [ ] Each category will have a default instruction text in the Category Information spreadsheet (Kelly)
- [ ] Cards that need instructions that are not the default will have their own instructions in the spreadsheet (Follin)
- [x] The API will provide either the default or the custom instructions for each card (Robbie)
- [ ] The instructions will be displayed on the cards are they are viewed in the app. (Kenan and/or Asher)

**Comment by Soyokaze-42** [comment]
I put a place for the default instructions on the Category Information sheet in the Google spreadsheet we've been using. Once we merge #63, this will be available from the backend.

**Comment by asherlloyd** [comment]
Resolved by #63.
