### ISSUE TITLE
[Feat] Static Site Pages

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#73]
**Is your feature request related to a problem? Please describe.**
No?

**Describe the solution you'd like**
Add the static pages/ content from the Canva design (and the footer)

**Describe alternatives you've considered**
n/a

**Additional context**
These tasks may be outside MVP but they are good first issues for students in my class to start working on.

- [ ] #74
- [ ] #76
- [ ] #77
- [ ] My Story Section
- [ ] Further Reading / Resources Page
- [ ] Add Analytics

**Comment by asherlloyd** [comment]
Closing.
