### ISSUE TITLE
[story] Design Daily Deck UI for Info Page

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#96]
As a: non-authenticated (guest) user
I want: to see today's prayer deck
So that: I can get a feel for the site and pray those prayers. 

AC:
- [x] Design 4 options of the UI on paper
- [x] Get @kenancasey's feedback on which option to use
- [x] Design a higher quality version of the chosen design on paper or Figma 
- [x] Get @kenancasey's approval for final design

**Comment by savannah-martin** [comment]
![image](https://github.com/PrayTeam/scriptured-prayer/assets/78399457/7703c4f8-2d92-4a39-a889-0f8814c2763e)

![image](https://github.com/PrayTeam/scriptured-prayer/assets/78399457/54eea857-9e0d-4933-add2-8dabcfa67113)

**Comment by savannah-martin** [comment]
[https://www.figma.com/file/sC6zm4Oh7kV9B4DjEbB4hN/Daily-Deck?type=design&node-id=31-233&mode=design&t=Ofn9Bz0u528PWXsr-0](url)
