### ISSUE TITLE
[Feat] Design and Develop a Navigation Bar in the Header

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#97]
**Is your feature request related to a problem? Please describe.**
Users should be able to navigate between the top-level pages.

**Describe the solution you'd like**
Design and develop a nav (bar) to allow users to navigate between the top-level routes. 

**Describe alternatives you've considered**
There's a nav in the footer, but we need more discoverability and easier navigation between the pages.  

**Additional context**
This isn't in the Canva design (but I strongly think it should be). 

- [ ] #100 
- [ ] Create a Nav component
- [ ] Style Nav Bar
- [ ] Integrate Nav Bar into (all?) pages

**Comment by asherlloyd** [comment]
Closing as completed.
